Issue 78: Replace deprecated notify()
FormulasQuestion/moodle-qtype_formulas pull request #79
Opened 2023-03-09 22:45 UTC by golenkovm

This resolves #78

2023-03-10 05:38 UTC, PhilippImhof commented
Thank you for your contribution. We will integrate that with the next release.

2023-03-10 07:01 UTC, PhilippImhof requested changes
Looks good to me, thanks for the contribution. Could you please just change back the é in Jean-Michel's name?

2023-03-10 07:01 UTC, PhilippImhof commented on question.php
> + * @copyright  2012 Jean-Michel V�drine
```suggestion
 * @copyright  2012 Jean-Michel Védrine
```

2023-03-10 07:01 UTC, PhilippImhof commented on question.php
> + * @copyright  2012 Jean-Michel V�drine
Somehow the é got lost, probably an encoding problem.

2023-03-10 07:31 UTC, golenkovm commented on question.php
> + * @copyright  2012 Jean-Michel V�drine
Yeah, I think this is encoding thing. My dev env is Phpstorm under Ubuntu and this letter was swapped automatically when I opened the codebase. Tried to undo but Phpstorm didn't allow me to do so. I'm happy to commit your suggested change.

2023-03-10 07:35 UTC, golenkovm commented on question.php
> + * @copyright  2012 Jean-Michel V�drine
Hmm, looks like the suggested change did nothing. I still can see a letter with question mark in it as an old letter and é as a new value

2023-03-10 07:37 UTC, PhilippImhof approved these changes
Thanks!

2023-03-10 07:52 UTC, PhilippImhof commented
Could you please sync your fork and rebase the branch? (It seems I cannot commit to this PR.)

2023-03-10 07:55 UTC, PhilippImhof commented on question.php
> + * @copyright  2012 Jean-Michel V�drine
For me, it looks good now. I'll have a look at it again, once the branch is rebased.

2023-03-16 03:06 UTC, golenkovm commented
Looks to be rosolved now.
Cheers

2023-03-16 07:54 UTC, PhilippImhof commented
Perfect. Thanks for your contribution.

2023-03-16 07:55 UTC, merged